locastic_sylius_store_locator_plugin_admin_store:
    resource: |
        alias: locastic_sylius_store_locator_plugin.store
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: locastic_sylius_store_locator_plugin_admin_store
        except: ['show']
        vars:
            all:
                header: locastic_sylius_store_locator_plugin.ui.stores
                subheader: locastic_sylius_store_locator_plugin.ui.manage_stores
            index:
                icon: 'map marker alternate'
    type: sylius.resource