imports:
    - { resource: "@LocasticSyliusStoreLocatorPlugin/Resources/config/resources_pickup_at_store.yml" }

services:
    locastic_sylius_store_locator_plugin.form.extension.type.shipment:
        class: Locastic\SyliusStoreLocatorPlugin\Form\Extension\Checkout\ShipmentTypeExtension
        arguments:
            - '@translator'
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType }

    locastic_sylius_store_locator_plugin.form.extension.type.shipping_method:
        class: Locastic\SyliusStoreLocatorPlugin\Form\Extension\ShippingMethodTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType }