sylius_shipping:
    resources:
        shipping_method:
            classes:
                model: Locastic\SyliusStoreLocatorPlugin\Entity\ShippingMethod
        shipment:
            classes:
                model: Locastic\SyliusStoreLocatorPlugin\Entity\Shipment


services:
    app.fixture.example_factory.shipping_method:
        class: Locastic\SyliusStoreLocatorPlugin\Fixture\ShippingMethodFactory
        parent: 'sylius.fixture.example_factory.shipping_method'

    app.fixture.shipping_method:
        class: Locastic\SyliusStoreLocatorPlugin\Fixture\ShippingMethodFixture
        arguments:
            - '@sylius.manager.shipping_method'
            - '@app.fixture.example_factory.shipping_method'
        tags:
            - { name: sylius_fixtures.fixture }

