sylius_resource:
    resources:
        locastic_sylius_store_locator_plugin.store:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusStoreLocatorPlugin\Entity\Store
                form: Locastic\SyliusStoreLocatorPlugin\Form\Type\StoreType
            translation:
                classes:
                    model: Locastic\SyliusStoreLocatorPlugin\Entity\StoreTranslation






#sylius_resource:
#    resources:
#        bitbag_sylius_cms_plugin.block:
#            driver: doctrine/orm
#            classes:
#                model: BitBag\SyliusCmsPlugin\Entity\Block
#                form: BitBag\SyliusCmsPlugin\Form\Type\BlockType
#                repository: BitBag\SyliusCmsPlugin\Repository\BlockRepository
#                controller: BitBag\SyliusCmsPlugin\Controller\BlockController
#            translation:
#                classes:
#model: BitBag\SyliusCmsPlugin\Entity\BlockTranslation