sylius_resource:
    resources:
        locastic_sylius_store_locator_plugin.store:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusStoreLocatorPlugin\Entity\Store
                form: Locastic\SyliusStoreLocatorPlugin\Form\Type\StoreType
            translation:
                classes:
                    model: Locastic\SyliusStoreLocatorPlugin\Entity\StoreTranslation