services:
    locastic_sylius_store_locator_plugin.listener.admin.menu_builder:
        class: Locastic\SyliusStoreLocatorPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }


# forms
    locastic_sylius_store_locator_plugin.form.type.store:
        class: Locastic\SyliusStoreLocatorPlugin\Form\Type\StoreType
        arguments:
            - "%locastic_sylius_store_locator_plugin.model.store.class%"
            - ['locastic']
        tags:
            - { name: form.type }

    locastic_sylius_store_locator_plugin.form.type.translation.store:
        class: Locastic\SyliusStoreLocatorPlugin\Form\Type\Translation\PageTranslationType
        arguments:
            - "%locastic_sylius_store_locator_plugin.model.store_translation.class%"
            - ['locastic']
        tags:
            - { name: form.type }