services:
    locastic_sylius_store_locator_plugin.listener.admin.menu_builder:
        class: Locastic\SyliusStoreLocatorPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
